#!/bin/sh
ulimit -v 512000
cd /data/sites/ghctags.shishnet.org/ghctags
sleep 3 && sd_watcher --url http://127.0.0.1:8805/ --interval 30 --exit &
exec chpst -u shish:shish ../venv/bin/pserve production.ini
